### ISSUE TITLE
segfault when Plasma session restores

### ISSUE THREAD

**Issue by cuihaoleo** [davidedmundson/xembed-sni-proxy#10]
Arch Linux x86_64, Plasma 5.4.2, latest git code.

When Plasma restores last session (with xembedsniproxy running), xembedsniproxy will crash.

dmesg says:

```
[   58.289609] xembedsniproxy[2810]: segfault at 10 ip 000000000040dc69 sp 00007ffd0ca1b1a0 error 4 in xembedsniproxy[400000+15000]
```

**Comment by stativ** [comment]
Isn't this fixed by 3c39ea8? Plasma should no longer restore xembedsniproxy by itself.

**Comment by cuihaoleo** [comment]
Nope.
I'm using latest 11e8648 commit, it still crash at startup.

**Comment by cjacker** [comment]
Please refer to 

https://bugs.kde.org/show_bug.cgi?id=355463
